### ISSUE TITLE
Image Element Standards

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#82] opened 2019-06-27 22:36 UTC
﻿﻿﻿A graphical submit button. You must use the src attribute to define the source of the image and the alt attribute to define alternative text. You can use the height and width attributes to define the size of the image in pixels.

**Comment by edburyenegren-okta** [comment] 2020-06-08 20:52
Dupe of https://github.com/okta/odyssey/issues/373

**Closed by edburyenegren-okta** 2020-06-08 20:52 UTC
Labels: duplicate, request
