### ISSUE TITLE
Review transition timing and duration

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#56] opened 2019-06-27 22:26 UTC

**Comment by alexdahl-okta** [comment] 2019-07-05 22:37
Related: #16.

**Comment by edburyenegren-okta** [comment] 2019-07-10 19:57
@joejezowski-okta what's this a dupe of?

**Comment by edburyenegren-okta** [comment] 2019-09-17 23:08
Related: https://github.com/okta/odyssey/issues/193

**Comment by joejezowski-okta** [comment] 2019-09-30 21:14
No code commits, but we reviewed. We will revisit once branding is done.

**Closed** 2019-09-30 21:13 UTC
