### ISSUE TITLE
Table Headers

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#124] opened 2019-07-09 18:35 UTC
## Detailed description

> Is this issue related to a specific component?

Yes, tables.

> What did you expect to happen? What happened instead?

1. Table headers are Dark Grey and white.
2. "Edit" buttons disappear

> What browser & version are you experiencing this in?

Chrome, Version 71.0.3578.98 (Mac)

## Steps to reproduce the issue

1. Admin 
2. Settings

## Screenshots
Please include screenshots to help illuminate the issue.

<img width="1039" alt="Screen Shot 2019-07-09 at 11 30 43 AM" src="https://user-images.githubusercontent.com/49886075/60913990-70c25700-a23d-11e9-829a-155d0f55e772.png">

<img width="553" alt="Screen Shot 2019-07-09 at 11 34 33 AM" src="https://user-images.githubusercontent.com/49886075/60914070-9bacab00-a23d-11e9-9f26-6e1d3359c36a.png">

## Additional information

/admin/settings/account

**Comment by edburyenegren-okta** [comment] 2019-07-10 19:38
Dupe of https://github.com/okta/odyssey/issues/139 (These are forms.)

**Closed by edburyenegren-okta** 2019-07-10 19:38 UTC
Labels: bug, duplicate
