### ISSUE TITLE
Text+Select button bottom border is too dark

### ISSUE THREAD

**Issue by rchild-okta** [okta/odyssey#134] opened 2019-07-09 18:47 UTC
Example:
http://0.0.0.0:3000/form/edit-only-form

The "Text Select" example has a bottom border shadow that looks too dark.

**Comment by ganeshsomasundaram-okta** [comment] 2019-07-09 20:04
![image](https://user-images.githubusercontent.com/40774045/60919254-20052b00-a24a-11e9-9b75-a4d46a4ea965.png)

**Comment by edburyenegren-okta** [comment] 2019-07-10 19:33
Dupe of https://github.com/okta/odyssey/issues/129

**Closed by edburyenegren-okta** 2019-07-10 19:33 UTC
Labels: bug, duplicate
